#!/usr/bin/env bash
# =============================================================================
# BrickForce AI — Weapon Scaffolding Generator
# =============================================================================
# Generates a new weapon resource + scene stub from a template.
# Usage: bash tools/dev/create_weapon.sh <weapon_id> <weapon_class>
# Example: bash tools/dev/create_weapon.sh ak47 "Assault Rifle"
# =============================================================================

set -euo pipefail
GREEN='\033[0;32m'; BOLD='\033[1m'; NC='\033[0m'

WEAPON_ID="${1:-new_weapon}"
WEAPON_CLASS="${2:-Assault Rifle}"
DISPLAY_NAME="${WEAPON_ID//_/ }"
RESOURCE_PATH="resources/weapons/${WEAPON_ID}.tres"
SCRIPT_PATH="src/gameplay/weapons/firearms/${WEAPON_ID}_weapon.gd"

echo -e "${BOLD}Creating weapon: $WEAPON_ID${NC}"

# ── Generate WeaponData resource ──────────────────────────────────────────────
cat > "$RESOURCE_PATH" << RESOURCE
[gd_resource type="Resource" script_class="WeaponData" load_steps=2 format=3]

[ext_resource type="Script" path="res://src/data/weapons/weapon_data.gd" id="1"]

[resource]
script = ExtResource("1")
weapon_id = "${WEAPON_ID}"
display_name = "${DISPLAY_NAME^}"
weapon_class = 0
damage = 35.0
headshot_multiplier = 2.5
range = 200.0
rpm = 600
mag_size = 30
reserve_max = 180
ammo_type = "rifle_ammo"
reload_time = 2.4
is_hitscan = true
RESOURCE

echo -e "${GREEN}[OK]${NC} Resource: $RESOURCE_PATH"

# ── Generate Weapon Script ─────────────────────────────────────────────────────
cat > "$SCRIPT_PATH" << SCRIPT
## ${WEAPON_ID} — ${DISPLAY_NAME^} (${WEAPON_CLASS})
## Generated by create_weapon.sh
## Customize _perform_shot() and _on_fire_fx() for unique behaviour.

class_name ${WEAPON_ID^}Weapon
extends WeaponBase


func _ready() -> void:
	super._ready()
	# weapon_data is assigned via the inspector or ResourceLoader.


func _on_fire_fx() -> void:
	super._on_fire_fx()
	# Add unique fire effects here.


func _perform_shot(direction: Vector3) -> void:
	super._perform_shot(direction)
	# Add unique projectile/hitscan logic here.
SCRIPT

echo -e "${GREEN}[OK]${NC} Script: $SCRIPT_PATH"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Open Godot → Resources/$RESOURCE_PATH → configure stats"
echo "  2. Create scene: scenes/weapons/${WEAPON_ID}.tscn"
echo "  3. Attach script: $SCRIPT_PATH"
echo "  4. Add to loot tables in resources/missions/"
