#!/usr/bin/env bash
# =============================================================================
# BrickForce AI — Character Scaffolding Generator
# =============================================================================
# Usage: bash tools/dev/create_character.sh <character_id> <faction>
# Example: bash tools/dev/create_character.sh ghost_operative ally
# =============================================================================

set -euo pipefail
GREEN='\033[0;32m'; BOLD='\033[1m'; NC='\033[0m'

CHAR_ID="${1:-new_character}"
FACTION="${2:-enemy}"  # player | ally | enemy
FACTION_INT=2
case "$FACTION" in
  player) FACTION_INT=0 ;;
  ally)   FACTION_INT=1 ;;
  enemy)  FACTION_INT=2 ;;
esac

DISPLAY_NAME="${CHAR_ID//_/ }"
RESOURCE_PATH="resources/characters/${CHAR_ID}.tres"
SCRIPT_PATH="src/gameplay/characters/enemy/${CHAR_ID}.gd"
[ "$FACTION" = "player" ] && SCRIPT_PATH="src/gameplay/characters/player/${CHAR_ID}.gd"
[ "$FACTION" = "ally" ]   && SCRIPT_PATH="src/gameplay/characters/enemy/${CHAR_ID}.gd"

echo -e "${BOLD}Creating character: $CHAR_ID (${FACTION})${NC}"

cat > "$RESOURCE_PATH" << RESOURCE
[gd_resource type="Resource" script_class="CharacterData" load_steps=2 format=3]

[ext_resource type="Script" path="res://src/data/characters/character_data.gd" id="1"]

[resource]
script = ExtResource("1")
character_id = "${CHAR_ID}"
display_name = "${DISPLAY_NAME^}"
faction = ${FACTION_INT}
max_health = 100.0
base_armor = 0.0
move_speed = 5.0
sprint_multiplier = 1.7
ai_personality = 2
detection_range = 30.0
hearing_range = 20.0
reaction_time = 0.4
accuracy = 0.75
RESOURCE

echo -e "${GREEN}[OK]${NC} Resource: $RESOURCE_PATH"

cat > "$SCRIPT_PATH" << SCRIPT
## ${CHAR_ID} — ${DISPLAY_NAME^} (${FACTION})
## Generated by create_character.sh

class_name ${CHAR_ID^}Character
extends AICharacter


func _ready() -> void:
	super._ready()
	# Custom initialization here.
SCRIPT

echo -e "${GREEN}[OK]${NC} Script: $SCRIPT_PATH"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Configure stats in: $RESOURCE_PATH"
echo "  2. Create scene: scenes/characters/${CHAR_ID}.tscn"
echo "  3. Set character_data export on the root node"
